bnbblog/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
     url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

dog/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from dog import views
from .views import (
    CottageLikeToggle,
)


app_name = 'dog'
urlpatterns = [
    #Main
    url(r'^$', views.index, name='index'),
    #Region URLs
    url(r'^regions/$', views.regions, name='regions'),
    url(r'^add_region/$', views.add_region, name='add_region'),
    url(r'^region/(?P<region_name_slug>[\w\-]+)/$', views.show_region, name='show_region'),
    #Cottage URLs
    url(r'^region/(?P<region_name_slug>[\w\-]+)/add_cottage/$', views.add_cottage, name='add_cottage'),
    url(r'^cottage/(?P<cottage_name_slug>[\w\-]+)/$', views.show_cottage, name='show_cottage'),
    url(r'^cottage/(?P<cottage_name_slug>[\w\-]+)/like/$', CottageLikeToggle.as_view(), name='like-toggle'),
    url(r'^browse_cottages/$', views.browse_cottages, name='browse_cottages'),
    url(r'^mostviewed/$', views.mostviewed, name='mostviewed'),
    url(r'^mostliked/$', views.mostliked, name ='mostliked'),
    url(r'^cottage/(?P<cottage_name_slug>[\w\-]+)/review/$', views.review, name='review'),
    url(r'^cottage/(?P<cottage_name_slug>[\w\-]+)/sign/$', views.sign, name='sign'),
    url(r'^suggest_cottage/$', views.suggest_cottage, name='suggest_cottage'),
    ]

dog_project/urls.py
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from dog import views


urlpatterns = [
    
    # INDEX [HOME]
    url(r'^$', views.index, name='index'),
    
    # INCLUDE DOG APP URLS
    # [We have kept all of the urls in the app]
    url(r'^dog/', include('dog.urls')),

    
    
    # ADMIN SITE
    url(r'^admin/', admin.site.urls),
    # REGISTRATION
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$', views.MyRegistrationView, name='registration_register'),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

dog/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from django.utils.text import slugify
from django.contrib.auth.models import User
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files.base import ContentFile
from django.core.files import File
from django.utils import timezone
from django.conf import settings
from django.core.urlresolvers import reverse
import os
#Region model
class Region(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Region, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

#Cottage Model
class Cottage(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=128, blank=True)
    image = models.ImageField(upload_to='cottages', blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='cottage_likes')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    region = models.ForeignKey(Region)
    address = models.CharField(max_length=128, blank=True)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Cottage, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name
    #urls Helper Classses to handkle the like toggle button
    def get_absolute_url(self):
        return reverse("dog:show_cottage", args=[self.slug])

    def get_api_like_url(self):
        return reverse("dog:api_like_cottage", args=[self.slug])


#Comment Model
class Comment(models.Model):
    name = models.CharField(max_length=20, blank=True)
    comment = models.TextField(blank=True)
    date_added = models.DateTimeField(default=timezone.now)
    cottage = models.ForeignKey(Cottage, related_name='comments',blank=True, null=True)

    def __str__(self):
        return self.name

#UserProfile Model


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

def __str__(self):
        return self.user.username

dog/forms.py
from django import forms
from dog.models import Comment
from dog.models import Cottage
from dog.models import Region
from dog.models import UserProfile
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe



class CommentForm (forms.Form):
    name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder':'Name'}))
    comment = forms.CharField (widget=forms.Textarea(attrs={'class' : 'form-control' ,'placeholder' : 'Comment'}))
    date_added = forms.DateTimeField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Comment
        exclude = ('cottage',)

class RegionForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the region name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Region
        fields = ('name',)

class CottageForm(forms.ModelForm):
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Cottage
        fields = ('name', 'image', 'address')
        exclude = ('region','user', 'likes', 'views')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

dog/views.py
from registration.backends.simple.views import RegistrationView
from django.shortcuts import render_to_response,  get_object_or_404, render, redirect
from django.http import HttpResponse
from dog.models import Region, Comment, Cottage
from dog.forms import RegionForm, CottageForm, CommentForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
from django.template import RequestContext
from django.views.generic import RedirectView
from django.db.models import Count
#Main screen View
def index(request):

   request.session.set_test_cookie()
   region_list = Region.objects.order_by('-likes')[:5]
   cottage_list = Cottage.objects.order_by('-views')[:5]
   context_dict = {'cottages':cottage_list, 'regions':region_list}

   #visitor_cookie_handler(request)
   #context_dict['visits'] = request.session['visits']

   #print(request.session['visits'])

   response = render(request, 'dog/index.html', context=context_dict)
   return response

#View requesting the list of the cottages
def get_cottage_list(max_results=0, starts_with=''):
    cottage_list = []
    if starts_with:
        cottage_list = Cottage.objects.filter(name__istartswith=starts_with)
    if max_results > 0:
        if len(cottage_list) > max_results:
            cottage_list = cottage_list[:max_results]
    return cottage_list

#View displaying the list of suggested cottages
def suggest_cottage(request):
    cottage_list = []
    starts_with = ''
    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cottage_list = get_cottage_list(8, starts_with)

    return render(request, 'dog/searchresults.html', {'cottages': cottage_list })

#View displaying List of available regions
def regions(request):
   context_dict = {}
   #visitor_cookie_handler(request)
   #context_dict['visits'] = request.session['visits']
   return render(request, 'dog/regions.html', context=context_dict)

#View displaying the particular selected region
def show_region(request, region_name_slug):
   context_dict = {}
   try:
      region = Region.objects.get(slug=region_name_slug)
      cottages = Cottage.objects.filter(region=region)
      context_dict['cottages'] = cottages
      context_dict['region'] = region
   except Region.DoesNotExist:
      context_dict['cottages'] = None
      context_dict['region'] = None

   return render(request, 'dog/region.html', context_dict)

#View displaying the particular selected cottage
def show_cottage(request, cottage_name_slug):
   context_dict = {}
   try:
      cottage = Cottage.objects.get(slug=cottage_name_slug)
      comments = Comment.objects.filter(cottage=cottage)
      context_dict['comments'] = comments
      context_dict['cottage'] = cottage
   except Cottage.DoesNotExist:
      context_dict['comments'] = None
      context_dict['cottage'] = None

   return render(request, 'dog/cottage.html', context_dict)

#View handling the like toggle button
class CottageLikeToggle(RedirectView):
    def get_redirect_url(self, cottage_name_slug):
        print(self)
        slug = cottage_name_slug
        print(slug)
        obj = get_object_or_404(Cottage, slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated():
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_

#View using RegionForm handling new region requests
def add_region(request):
   form = RegionForm()

   if request.method =='POST':
      form = RegionForm(request.POST)

      if form.is_valid():
         reg = form.save(commit=True)
         print(reg, reg.slug)

         return index(request)

      else: print(form.errors)
   return render(request, 'dog/add_region.html', {'form':form})

#View displaying all of the cottage from  the database
def browse_cottages(request):
      context_dict = {}
      try:
            cottages = Cottage.objects.all()
            context_dict['cottages'] = cottages
      except Cottage.DoesNotExist:
            context_dict['cottages'] = None


      return render(request, 'dog/browse_cottages.html', context_dict)


#-Sorting all the cottages based on the number of likes
def mostliked(request, ):
      context_dict = {}
      try:
            mlcottages = Cottage.objects.all()
            mlcottages = Cottage.objects.annotate(like_count=Count('likes')).order_by('-like_count')
            context_dict['cottages'] = mlcottages
      except Cottage.DoesNotExist:
            context_dict['cottages'] = None
      print(mlcottages)

      return render(request, 'dog/browse_cottages.html', context_dict)

#-Sorting all the cottages based on the number of views
def mostviewed(request):
      context_dict = {}
      try:
            mvcottages = Cottage.objects.all()
            mvcottages = Cottage.objects.annotate(view_count=Count('views')).order_by('-view_count')
            context_dict['cottages'] = mvcottages
      except Cottage.DoesNotExist:
            context_dict['cottages'] = None

      return render(request, 'dog/browse_cottages.html', context_dict)


#View using CottageForm handling new cottage requests
def add_cottage(request, region_name_slug):
      try:
            region = Region.objects.get(slug=region_name_slug)
      except Region.DoesNotExist:
            region = None

      form = CottageForm()
      if request.method == 'POST':
            form = CottageForm(request.POST)
            if form.is_valid():
                  if region:
                        cottage = form.save(commit=False)
                        cottage.region = Region.objects.get(slug=region_name_slug)
                        cottage.views = 0
                        if 'image' in request.FILES:
                              cottage.image = request.FILES['image']
                              cottage.save()
                              return show_region(request, region_name_slug)
                  else:
                        print(form.errors)

      context_dict = {'form':form, 'region':region}
      return render(request, 'dog/add_cottage.html', context_dict)


#Read Reviews view containing comments sorted by the date-added
def review(request, cottage_name_slug):
      context_dict = {}
      try:
            cottage = Cottage.objects.get(slug=cottage_name_slug)
      except CottageDoesNotExist:
            cottage = None

      comments = Comment.objects.order_by('-date_added')
      context = {'comments' : comments, 'cottage':cottage}
      return render (request, 'dog/review.html', context)

#Create Comment view containing a reference to Comment form
def sign(request, cottage_name_slug):
      try:
            cottage = Cottage.objects.get(slug=cottage_name_slug)
      except Cottage.DoesNotExist:
            cottage = None

      form = CommentForm()
      if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                  if cottage:
                     new_comment = Comment(name=request.POST['name'],comment=request.POST['comment'])
                     new_comment.cottage = cottage
                     new_comment.save()
                     return show_cottage(request, cottage_name_slug)
                  else:
                     print(form.errors)
      else:
            form = CommentForm()

      context_dict = {'form' : form, 'cottage': cottage}
      return render (request, 'dog/sign.html', context_dict)


@login_required
def restricted(request):
   return render(request, 'dog/restricted.html', {})


class MyRegistrationView(RegistrationView):
   def get_success_url(self, user):
      return '/dog/'

templates/dog/about.html
{% extends 'dog/base.html' %}
{% load staticfiles %}


{% load dog_template_tags %}
{% block title_block %}

Regions

{% endblock %}


{% block body_block %}


<h1 align ="center">Regions</h1>


{% block sidebar_block %}

{% get_region_list region %}

{% endblock %}

{% endblock %}

templates/dog/base.html
<!DOCTYPE html>
{% load dog_template_tags %}

{% load staticfiles %}
<html lang="en">
<head>
  <!-- meta-->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="{% static 'images/scotty.ico' %}">

  <meta charset="utf-8">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
  <!-- scripts for easy autocomplete -->


  <!-- CSS file -->
  <link rel="stylesheet" href="{% static 'css/easy-autocomplete.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/album.css' %}" type="text/css" media="screen, projection" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" media="screen, projection" />


  <!-- Additional CSS Themes file - not required-->
  <link rel="stylesheet" href= "{% static 'css/easy-autocomplete.themes.min.css' %}">

  <!-- scripts for easy autocomplete end -->

  <!-- Bootstrap CSS -->
  <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom styles for this template -->
  <!-- <link href= "http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet"> -->

 <!-- fonts -->
 <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin" rel="stylesheet">


  <link rel="stylesheet" href="{% static 'css/main.css'%}" type="text/css" media="screen, projection" />

  <link href="http://v4-alpha.getbootstrap.com/examples/signin/signin.css" rel="stylesheet">
  <!-- JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!-- title -->
  <title>
    SCOTTY
    {% block title_block %}
    {% endblock %}
  </title>

</head>
<body id="bodyblock" >
  <!--- navbar -->
  <div class="container menu">

    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <a class="navbar-brand" href="/">
        <div>
          <img src="{% static "images/scotty-21.png" %}" width="80" alt="scotty logo" />
        </div>
      </a>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">

        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dog:regions' %}">Regions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dog:browse_cottages' %}">Browse all Cottages</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dog:add_region' %}">Add Region</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_logout' %}">Logout </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registration_register' %}">Register </a>
          </li>
          {% endif %}
        </ul>


      </div>

    </nav>

  </div>


  <!--- main content area -->

  <div >
    <div class="row">
      <div class="container">
        <h1 >&nbsp;</h1>
        {% block body_block %}
        {% endblock %}
      </div>
    </div>
</div>
    <style>

    #bodyblock {
      background-image: url("{% static 'images/background.png' %}");
      background-color: #e9ece5;
      background-image opacity: 0.2;

    }
    #footertext{
      font-size: 14px;
      color: gray;
      opacity: 0.6;

    }

    #backtotop{
      color: #00CC66;
    }


    </style>


    <!--- footer area -->

    <footer class="text-muted">
      <div class="container">
        {% block footer %}

        <div class="row">
          <div  class="col-sm">
          <p ><a id="footertext" href= "https://github.com/aive/scotty.git">Scotty on Github</a></p>
          <a id="footertext" href="mailto:#">2288799K@student.gla.ac.uk</a>
          </div>
          <div  class="col-sm">
            <strong id="footertext"><center>It takes 4 to Django </p> <a href="mailto:#">scotty@dog.uk</a></center></strong>
          </div>
          <div class="col-sm">
            <div class="float-right">
            <center><a id="backtotop" href="#">Back to top</a></center>
          </div>
          </div>
        </div>
      </div>

    </footer>
    {% endblock %}



      <!-- Bootstrap core JavaScript -->

      <!-- our google maps script-->
      <script src= "{% static 'js/maps.js' %}> </script>
      <!--our google searchbar script
      <script src= "static/js/searchbar.js"> </script>


      <!--ajaxing-->
      <!-- <script src="{% static "js/jquery.min.js" %}"></script> -->
      <!-- <script src="{% static "js/scotty-ajax.js" %}"></script> -->

      <!--ajax
      <script
      src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
      </script>


      <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
      <script
      src=
      "http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
      </script>

      <!-- jQuery CDN for easyAutocomplete -->
      <!-- <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script> -->
      <!-- JS file -->
      <script src="{% static 'js/jquery.easy-autocomplete.min.js' %}"></script>
      <script src="{% static 'js/scotty-ajax.js' %}"></script>
      <!-- end jQuery CDN for easyAutocomplete -->

      <!-- jQuery first, then Tether, then Bootstrap JS. -->
      <!-- <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script> -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>



      </div>
      </body>
      </html>

templates/dog/index.html
{% extends 'dog/base.html' %}
{% load staticfiles %}

{% block title_block %}
Home/Search
{% endblock %}
{% block body_block %}


<style>
/* index page */
#cottages {
  font-size: 20px;
  color: #262D06;
  /* color: #3ab7a2;*/
}

     ul{
    list-style-type: none;
    text-align: center;
    text-rendering: auto;
    color: #A0EACA;
    }

    a {
      color: #3ab7a2;
      /* color: #3ab7a2;*/
    }


</style>



<section>
	<div class="jumbotron" style="text-align: center">
    <img src="{% static "images/scotty-22.png" %}" width="250" alt="scotty" />
    <img src="{{ MEDIA_URL }}sketches/sketch-01.png" width="500" alt='Image of scotty'/>
    <h1 >Type to find cottages. </h1>
    <!-- <img id='bone' src="{{ MEDIA_URL }}sketches/sketch-14.png" width="500" alt='Image of a bone'/> -->


    <form>
    <h3 class="centered" ><input  type="text" name="suggestion" value="" id="suggestion" /></h3>
    </form>
    <div id="cottages"></div>

    <div class="dropdown w3-flat-pumpkin">
      <hr>
			<button class="dropbtn">Go to:</button>
			<div class="dropdown-content">
				<a href="{%url 'dog:regions' %}">Regions</a>
				<a href="{%url 'dog:browse_cottages' %}">All</a>
			</div>

		</div>
	</div>
</section>







<!--- search bar
<div class="container w3-display-container searchcontent">

  <form class="search w3-display-middle">

    <select id="region" class="button">
      <option>--select region</option>
      <option value='region1'>Region 1</option>
      <option value='region2'>Region 2</option>
    </div>
  </div>
</select>

<input class="input" type="text" name="price_from">
<input class="input" type="text" name="price_to">
<input class="button searchbutton " type="submit" value='Search'>


</form>
</div>
-->
<!-- search bar
<div class="search-box-wrapper">
  <input type="text" id="maxsize" placeholder="Search…" class="search-box-input"  >
  <script src="{% static 'js/findplace.js' %}"></script>
  <button width="500" class="search-box-button">&#128269;</button>
</div>
-->
<!-- another Rango book search bar-->


<!--h2>Type to fetch.</h2-->




{% endblock %}

templates/dog/region.html
<!DOCTYPE html>
{% extends 'dog/base.html' %}
{% load staticfiles %}

{% block title_block %}
	{{ region.name }}
{% endblock %}

{% block body_block %}





	{% if region %}

	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" type="text/css" media="screen, projection" />
	<link rel="stylesheet" href="{% static "css/album.css" %}" type="text/css" media="screen, projection" />

	<!-- Bootstrap core CSS -->
	<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="album.css" rel="stylesheet">

	<section class="jumbotron text-center">
		<div class="container">
			<h1 class="jumbotron-heading">Dogfriendly cottages</h1>
			<p class="lead text-muted">Here are some wonderful dogfriendly cottages in the region. Check them out!</p>
			{% if user.is_authenticated %}
			<a href="{% url 'dog:add_cottage' region.slug %}">Add a Cottage</a>
		{% endif %}
		</div>
	</section>

	<div class="album text-muted">
		<div class="container">

			<div class="row">
		{% if cottages %}
		{% for cottage in cottages %}


					<div class="card">
						<!-- <img data-src="holder.js/100px280/thumb" alt="Card image cap"> -->
						<div class="cropthumb">
						<a target="_blank" href="{% url 'dog:show_cottage' cottage.slug %}">
							<img id="thumb" src="{{ MEDIA_URL }}{{ cottage.image }}" alt="Image of {{ cottage.name }}"	width="340" >
					  </a>
					</div>
						<div class="desc">{{ cottage.name }}</div>
						<p class="card-text">{{ cottage.description }}</p>
					</div>

<!--
		<div class="responsive">
			<div class="gallery">
			  <a target="_blank" href="{% url 'dog:show_cottage' cottage.slug %}">
				<img src="{{ MEDIA_URL }}{{ cottage.image }}" alt="Image of {{ cottage.name }}" >
			  </a>
			  <div class="desc">{{ cottage.name }}</div>
			</div>
		</div>

		<div class="clearfix"></div>
-->

		{% endfor %}
	</div>
	</div>
	</div>
		{% else %}
			<strong>No cottages currently in region.</strong>
		{% endif %}
	</div>


	{% else %}
		The specified Region does not exist!
	{% endif %}


	</body>
	</html>
	{% endblock %}

templates/dog/regs.html

{% if regs %}
	{% for r in regs %}
	<div>
		<a href="{% url 'dog:show_region' r.slug %}" class="list-group-item list-group-item-action"> {{ r.name }}</a>
	</div>
	{% endfor %}
{% endif %}

templates/dog/review.html
{% extends 'dog/base.html' %}

{% load staticfiles%}


{% block body_block %}

    
<meta charset="utf-8">
    
<meta http-equiv="X-UA-Compatible" content="IE=edge">
   
 <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
   
 <meta name="description" content="">
    
<meta name="author" content="">

   
 <title>Review our BnB</title>

    
<!-- Bootstrap core CSS -->
   
 <link href="{% static 'review/bootstrap.min.css' %}"rel="stylesheet"> 
   
 <!-- Bootstrap theme -->
    
<link href="{% static 'review/bootstrap-theme.min.css'%} " rel="stylesheet">

   
 <!-- Custom styles for this template -->
    <link href="{% static 'review/theme.css'%}" rel="stylesheet">

  
</head>

  <body>

    <div class="container theme-showcase" role="main">

      <div class="jumbotron">
      
  <h1>Reviews for {{cottage.slug }}</h1>
       
 <a type="button" class="btn btn-link" href="{% url 'dog:sign' cottage.slug %}">Sign in to send your reviews</a>
     
 </div>


      
{% if cottage %}
            
	{% if comments %}
            
		{% for c in comments %}
            
		<div class="page-header">
              
	<h1>{{c.name}}</h1>
            
		</div>
            
	<div class="well">
              
	<p>{{c.comment}}.</p>
            
	</div>
            
		{% endfor %}
            
	{% endif %}
            
	{% endif %}
      
	</div> <!-- /container -->

  
	</body>

  
	{% endblock %}


templates/dog/search-results.html
{% extends 'dog/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Search results
{% endblock %}

{% block body_block %}

	<h1>Search Results</h1>
	<p>Results placeholder</p>

</div>




{% endblock %}